name: Run yarn test
on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/yarn.lock') }}

      - name: Install modules
        run: yarn

      - name: Run tests
        run: yarn test
